### ISSUE TITLE
Error: Error serializing `.base_url` returned from `getServerSideProps` in "/en". Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

### ISSUE THREAD

**Issue by gabinfinity** [Nareshe31/zflix-app#20]
Can you help me? Please? Im getting this error

![image](https://user-images.githubusercontent.com/59806981/209455042-927bc804-7a30-4d23-a331-bbe1d9bd0d24.png)

**Comment by Nareshe31** [comment]
Hi,

Which branch are you using?

**Comment by Nareshe31** [comment]
Please add below values in .env.local file

BASE_URL=
TMDB_API_KEY=
NEXT_PUBLIC_TMDB_API_KEY=
NEXT_PUBLIC_BACKEND_URI_V3=
NEXT_PUBLIC_BACKEND_URI_V2=
